namespace Wh40kCharacterList.Core.IngameEntities.CharacterProperties;

static public class SkillData
{
    public static bool MustBeBasicByDefault(Skill skill)
    {
        return skill switch
        {
            Skill.Acrobatics => false,
            Skill.Awareness => true,
            Skill.Barther => true,
            Skill.Blather => false,
            Skill.Carouse => true,
            Skill.Charm => true,
            Skill.ChemUse => false,
            Skill.Ciphers => false,
            Skill.Climb => true,
            Skill.Command => true,
            Skill.Commerce => false,
            Skill.CommonLore => false,
            Skill.Concealment => true,
            Skill.Contortionist => true,
            Skill.Deceive => true,
            Skill.Demolition => false,
            Skill.Disguise => true,
            Skill.Dodge => true,
            Skill.Drive => false,
            Skill.Evaluate => true,
            Skill.ForbiddenLore => false,
            Skill.Gamble => true,
            Skill.Inquiry => true,
            Skill.Interrogation => false,
            Skill.Intimidate => true,
            Skill.Invocation => false,
            Skill.LipReading => false,
            Skill.Literacy => false,
            Skill.Logic => true,
            Skill.Medicae => true,
            Skill.Navigation => true,
            Skill.Performer => true,
            Skill.Pilot => true,
            Skill.Psyniscience => true,
            Skill.ScholasticLore => true,
            Skill.Scrunity => true,
            Skill.Search => true,
            Skill.SecretTongue => false,
            Skill.Security => false,
            Skill.Shadowing => false,
            Skill.SilentMove => true,
            Skill.SleightOfHand => false,
            Skill.SpeakLanguage => false,
            Skill.Survival => false,
            Skill.Swim => true,
            Skill.TechUse => false,
            Skill.Tracking => false,
            Skill.Trade => false,
            Skill.Wrangling => false,
            _ => false,
        };
    }

    public static bool IsGroup(Skill skill)
    {
        return skill switch
        {
            Skill.Ciphers => true,
            Skill.CommonLore => true,
            Skill.Drive => true,
            Skill.ForbiddenLore => true,
            Skill.Navigation => true,
            Skill.Performer => true,
            Skill.Pilot => true,
            Skill.ScholasticLore => true,
            Skill.SecretTongue => true,
            Skill.SpeakLanguage => true,
            Skill.Trade => true,
            _ => false,
        };
    }

    public static Characteristic? GetAssisiatedDefaultCharacteristic(Skill skill)
    {
        return skill switch
        {
            Skill.Acrobatics => Characteristic.Agility,
            Skill.Awareness => Characteristic.Perception,
            Skill.Barther => Characteristic.FellowShip,
            Skill.Blather => Characteristic.FellowShip,
            Skill.Carouse => Characteristic.Toughness,
            Skill.Charm => Characteristic.FellowShip,
            Skill.ChemUse => Characteristic.Intelligence,
            Skill.Ciphers => Characteristic.Intelligence,
            Skill.Climb => Characteristic.Strenght,
            Skill.Command => Characteristic.FellowShip,
            Skill.Commerce => Characteristic.FellowShip,
            Skill.CommonLore => Characteristic.Intelligence,
            Skill.Concealment => Characteristic.Agility,
            Skill.Contortionist => Characteristic.Agility,
            Skill.Deceive => Characteristic.FellowShip,
            Skill.Demolition => Characteristic.Intelligence,
            Skill.Disguise => Characteristic.FellowShip,
            Skill.Dodge => Characteristic.Agility,
            Skill.Drive => Characteristic.Agility,
            Skill.Evaluate => Characteristic.Intelligence,
            Skill.ForbiddenLore => Characteristic.Intelligence,
            Skill.Gamble => Characteristic.Intelligence,
            Skill.Inquiry => Characteristic.FellowShip,
            Skill.Interrogation => Characteristic.WillPower,
            Skill.Intimidate => Characteristic.Strenght,
            Skill.Invocation => Characteristic.WillPower,
            Skill.LipReading => Characteristic.Perception,
            Skill.Literacy => Characteristic.Intelligence,
            Skill.Logic => Characteristic.Intelligence,
            Skill.Medicae => Characteristic.Intelligence,
            Skill.Navigation => Characteristic.Intelligence,
            Skill.Performer => Characteristic.FellowShip,
            Skill.Pilot => Characteristic.Agility,
            Skill.Psyniscience => Characteristic.Perception,
            Skill.ScholasticLore => Characteristic.Intelligence,
            Skill.Scrunity => Characteristic.Perception,
            Skill.Search => Characteristic.Perception,
            Skill.SecretTongue => Characteristic.Intelligence,
            Skill.Security => Characteristic.Agility,
            Skill.Shadowing => Characteristic.Agility,
            Skill.SilentMove => Characteristic.Agility,
            Skill.SleightOfHand => Characteristic.Agility,
            Skill.SpeakLanguage => Characteristic.Intelligence,
            Skill.Survival => Characteristic.Intelligence,
            Skill.Swim => Characteristic.Strenght,
            Skill.TechUse => Characteristic.Intelligence,
            Skill.Tracking => Characteristic.Intelligence,
            Skill.Trade => null,
            Skill.Wrangling => Characteristic.Intelligence,
            _ => null,
        };
    }
}
